# Generated by Django 4.0 on 2021-12-14 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_morte', models.DateField(blank=True, null=True, verbose_name='Morte')),
            ],
            options={
                'ordering': ['sobrenome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Entre com gênero do livro (ex: fantasia).', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Entre com o título do livro.', max_length=200)),
                ('sumario', models.TextField(help_text='Entre com uma breve descrição do livro', max_length=1000)),
                ('isbn', models.CharField(help_text='Número <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a> de 13 caracteres', max_length=11, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Selecione um gênero para o livro.', to='catalogo.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='LivroInstancia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID exclusivo para este livro específico em toda a biblioteca', primary_key=True, serialize=False)),
                ('edicao', models.CharField(max_length=200)),
                ('devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Em manutenção'), ('e', 'Em empréstimo'), ('d', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Disponibilidade do livro', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.livro')),
            ],
            options={
                'ordering': ['devolucao'],
            },
        ),
    ]
