# Generated by Django 4.0 on 2021-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroinstancia',
            name='idioma',
            field=models.CharField(blank=True, default='Português', max_length=20),
        ),
    ]
