# Generated by Django 4.0 on 2021-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_livroinstancia_idioma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['sobrenome', 'nome'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Gênero'},
        ),
        migrations.AlterModelOptions(
            name='livroinstancia',
            options={'ordering': ['devolucao'], 'verbose_name_plural': 'Instâncias de livros'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ManyToManyField(help_text='Selecione um gênero para o livro.', to='catalogo.Genero', verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sumario',
            field=models.TextField(help_text='Entre com uma breve descrição do livro', max_length=1000, verbose_name='Sumário'),
        ),
        migrations.AlterField(
            model_name='livroinstancia',
            name='devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Devolução'),
        ),
        migrations.AlterField(
            model_name='livroinstancia',
            name='edicao',
            field=models.CharField(max_length=200, verbose_name='Edição'),
        ),
    ]
