# Generated by Django 4.0 on 2021-12-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_autor_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='preposicao',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
