# Generated by Django 4.0 on 2021-12-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogo', '0004_autor_preposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroinstancia',
            name='mutuaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='preposicao',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Preposição'),
        ),
    ]
