# Generated by Django 4.0 on 2021-12-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_livroinstancia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livroinstancia',
            options={'ordering': ['devolucao'], 'permissions': (('can_mark_returned', 'Defina o livro como devolvido'),), 'verbose_name_plural': 'Instâncias de livros'},
        ),
    ]
