# Generated by Django 4.0 on 2021-12-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_livroinstancia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nome_meio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do meio'),
        ),
    ]
